name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  black:
    name: Check Black
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: rickstaa/action-black@v1
        with:
          black_args: "custom_components/smartrent --check"

  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-ha:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: HA validation
        uses: home-assistant/actions/hassfest@master
